

// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!



#include <stdbool.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
	// We also try to prevent mixing versions of shared uniffi header structs.
	// If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V6
	#ifndef UNIFFI_SHARED_HEADER_V6
		#error Combining helper code from multiple versions of uniffi is not supported
	#endif // ndef UNIFFI_SHARED_HEADER_V6
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V6
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V6 in this file.           ⚠️

typedef struct RustBuffer {
	uint64_t capacity;
	uint64_t len;
	uint8_t *data;
} RustBuffer;

typedef struct ForeignBytes {
	int32_t len;
	const uint8_t *data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
	int8_t code;
	RustBuffer errorBuf;
} RustCallStatus;

#endif // UNIFFI_SHARED_H


#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t data, int8_t poll_result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiRustFutureContinuationCallback(
				UniffiRustFutureContinuationCallback cb, uint64_t data, int8_t poll_result)
{
	return cb(data, poll_result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
typedef void (*UniffiForeignFutureFree)(uint64_t handle);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureFree(
				UniffiForeignFutureFree cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t handle);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceFree(
				UniffiCallbackInterfaceFree cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE
typedef struct UniffiForeignFuture {
    uint64_t handle;
    UniffiForeignFutureFree free;
} UniffiForeignFuture;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
typedef struct UniffiForeignFutureStructU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t callback_data, UniffiForeignFutureStructU8 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU8(
				UniffiForeignFutureCompleteU8 cb, uint64_t callback_data, UniffiForeignFutureStructU8 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
typedef struct UniffiForeignFutureStructI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t callback_data, UniffiForeignFutureStructI8 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI8(
				UniffiForeignFutureCompleteI8 cb, uint64_t callback_data, UniffiForeignFutureStructI8 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
typedef struct UniffiForeignFutureStructU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t callback_data, UniffiForeignFutureStructU16 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU16(
				UniffiForeignFutureCompleteU16 cb, uint64_t callback_data, UniffiForeignFutureStructU16 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
typedef struct UniffiForeignFutureStructI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t callback_data, UniffiForeignFutureStructI16 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI16(
				UniffiForeignFutureCompleteI16 cb, uint64_t callback_data, UniffiForeignFutureStructI16 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
typedef struct UniffiForeignFutureStructU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t callback_data, UniffiForeignFutureStructU32 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU32(
				UniffiForeignFutureCompleteU32 cb, uint64_t callback_data, UniffiForeignFutureStructU32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
typedef struct UniffiForeignFutureStructI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t callback_data, UniffiForeignFutureStructI32 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI32(
				UniffiForeignFutureCompleteI32 cb, uint64_t callback_data, UniffiForeignFutureStructI32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
typedef struct UniffiForeignFutureStructU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t callback_data, UniffiForeignFutureStructU64 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU64(
				UniffiForeignFutureCompleteU64 cb, uint64_t callback_data, UniffiForeignFutureStructU64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
typedef struct UniffiForeignFutureStructI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t callback_data, UniffiForeignFutureStructI64 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI64(
				UniffiForeignFutureCompleteI64 cb, uint64_t callback_data, UniffiForeignFutureStructI64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
typedef struct UniffiForeignFutureStructF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t callback_data, UniffiForeignFutureStructF32 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteF32(
				UniffiForeignFutureCompleteF32 cb, uint64_t callback_data, UniffiForeignFutureStructF32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
typedef struct UniffiForeignFutureStructF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t callback_data, UniffiForeignFutureStructF64 result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteF64(
				UniffiForeignFutureCompleteF64 cb, uint64_t callback_data, UniffiForeignFutureStructF64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
typedef struct UniffiForeignFutureStructPointer {
    void* returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructPointer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
typedef void (*UniffiForeignFutureCompletePointer)(uint64_t callback_data, UniffiForeignFutureStructPointer result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompletePointer(
				UniffiForeignFutureCompletePointer cb, uint64_t callback_data, UniffiForeignFutureStructPointer result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
typedef struct UniffiForeignFutureStructRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t callback_data, UniffiForeignFutureStructRustBuffer result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteRustBuffer(
				UniffiForeignFutureCompleteRustBuffer cb, uint64_t callback_data, UniffiForeignFutureStructRustBuffer result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
typedef struct UniffiForeignFutureStructVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureStructVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t callback_data, UniffiForeignFutureStructVoid result);

// Making function static works arround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteVoid(
				UniffiForeignFutureCompleteVoid cb, uint64_t callback_data, UniffiForeignFutureStructVoid result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_CLONE_BINDINGSADAPTER
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_CLONE_BINDINGSADAPTER
void* uniffi_slim_bindings_fn_clone_bindingsadapter(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_FREE_BINDINGSADAPTER
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_FREE_BINDINGSADAPTER
void uniffi_slim_bindings_fn_free_bindingsadapter(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSADAPTER_CONNECT
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSADAPTER_CONNECT
uint64_t uniffi_slim_bindings_fn_method_bindingsadapter_connect(void* ptr, RustBuffer config, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSADAPTER_CONNECT_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSADAPTER_CONNECT_ASYNC
uint64_t uniffi_slim_bindings_fn_method_bindingsadapter_connect_async(void* ptr, RustBuffer config
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSADAPTER_CREATE_SESSION
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSADAPTER_CREATE_SESSION
void* uniffi_slim_bindings_fn_method_bindingsadapter_create_session(void* ptr, RustBuffer config, RustBuffer destination, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSADAPTER_CREATE_SESSION_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSADAPTER_CREATE_SESSION_ASYNC
uint64_t uniffi_slim_bindings_fn_method_bindingsadapter_create_session_async(void* ptr, RustBuffer config, RustBuffer destination
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSADAPTER_DELETE_SESSION
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSADAPTER_DELETE_SESSION
void uniffi_slim_bindings_fn_method_bindingsadapter_delete_session(void* ptr, void* session, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSADAPTER_DELETE_SESSION_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSADAPTER_DELETE_SESSION_ASYNC
uint64_t uniffi_slim_bindings_fn_method_bindingsadapter_delete_session_async(void* ptr, void* session
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSADAPTER_DISCONNECT
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSADAPTER_DISCONNECT
void uniffi_slim_bindings_fn_method_bindingsadapter_disconnect(void* ptr, uint64_t connection_id, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSADAPTER_DISCONNECT_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSADAPTER_DISCONNECT_ASYNC
uint64_t uniffi_slim_bindings_fn_method_bindingsadapter_disconnect_async(void* ptr, uint64_t connection_id
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSADAPTER_ID
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSADAPTER_ID
uint64_t uniffi_slim_bindings_fn_method_bindingsadapter_id(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSADAPTER_LISTEN_FOR_SESSION
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSADAPTER_LISTEN_FOR_SESSION
void* uniffi_slim_bindings_fn_method_bindingsadapter_listen_for_session(void* ptr, RustBuffer timeout_ms, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSADAPTER_LISTEN_FOR_SESSION_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSADAPTER_LISTEN_FOR_SESSION_ASYNC
uint64_t uniffi_slim_bindings_fn_method_bindingsadapter_listen_for_session_async(void* ptr, RustBuffer timeout_ms
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSADAPTER_NAME
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSADAPTER_NAME
RustBuffer uniffi_slim_bindings_fn_method_bindingsadapter_name(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSADAPTER_REMOVE_ROUTE
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSADAPTER_REMOVE_ROUTE
void uniffi_slim_bindings_fn_method_bindingsadapter_remove_route(void* ptr, RustBuffer name, uint64_t connection_id, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSADAPTER_REMOVE_ROUTE_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSADAPTER_REMOVE_ROUTE_ASYNC
uint64_t uniffi_slim_bindings_fn_method_bindingsadapter_remove_route_async(void* ptr, RustBuffer name, uint64_t connection_id
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSADAPTER_RUN_SERVER
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSADAPTER_RUN_SERVER
void uniffi_slim_bindings_fn_method_bindingsadapter_run_server(void* ptr, RustBuffer config, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSADAPTER_RUN_SERVER_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSADAPTER_RUN_SERVER_ASYNC
uint64_t uniffi_slim_bindings_fn_method_bindingsadapter_run_server_async(void* ptr, RustBuffer config
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSADAPTER_SET_ROUTE
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSADAPTER_SET_ROUTE
void uniffi_slim_bindings_fn_method_bindingsadapter_set_route(void* ptr, RustBuffer name, uint64_t connection_id, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSADAPTER_SET_ROUTE_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSADAPTER_SET_ROUTE_ASYNC
uint64_t uniffi_slim_bindings_fn_method_bindingsadapter_set_route_async(void* ptr, RustBuffer name, uint64_t connection_id
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSADAPTER_STOP_SERVER
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSADAPTER_STOP_SERVER
void uniffi_slim_bindings_fn_method_bindingsadapter_stop_server(void* ptr, RustBuffer endpoint, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSADAPTER_SUBSCRIBE
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSADAPTER_SUBSCRIBE
void uniffi_slim_bindings_fn_method_bindingsadapter_subscribe(void* ptr, RustBuffer name, RustBuffer connection_id, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSADAPTER_SUBSCRIBE_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSADAPTER_SUBSCRIBE_ASYNC
uint64_t uniffi_slim_bindings_fn_method_bindingsadapter_subscribe_async(void* ptr, RustBuffer name, RustBuffer connection_id
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSADAPTER_UNSUBSCRIBE
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSADAPTER_UNSUBSCRIBE
void uniffi_slim_bindings_fn_method_bindingsadapter_unsubscribe(void* ptr, RustBuffer name, RustBuffer connection_id, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSADAPTER_UNSUBSCRIBE_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSADAPTER_UNSUBSCRIBE_ASYNC
uint64_t uniffi_slim_bindings_fn_method_bindingsadapter_unsubscribe_async(void* ptr, RustBuffer name, RustBuffer connection_id
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_CLONE_BINDINGSSESSIONCONTEXT
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_CLONE_BINDINGSSESSIONCONTEXT
void* uniffi_slim_bindings_fn_clone_bindingssessioncontext(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_FREE_BINDINGSSESSIONCONTEXT
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_FREE_BINDINGSSESSIONCONTEXT
void uniffi_slim_bindings_fn_free_bindingssessioncontext(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSSESSIONCONTEXT_DESTINATION
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSSESSIONCONTEXT_DESTINATION
RustBuffer uniffi_slim_bindings_fn_method_bindingssessioncontext_destination(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSSESSIONCONTEXT_GET_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSSESSIONCONTEXT_GET_MESSAGE
RustBuffer uniffi_slim_bindings_fn_method_bindingssessioncontext_get_message(void* ptr, RustBuffer timeout_ms, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSSESSIONCONTEXT_GET_MESSAGE_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSSESSIONCONTEXT_GET_MESSAGE_ASYNC
uint64_t uniffi_slim_bindings_fn_method_bindingssessioncontext_get_message_async(void* ptr, RustBuffer timeout_ms
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSSESSIONCONTEXT_INVITE
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSSESSIONCONTEXT_INVITE
void uniffi_slim_bindings_fn_method_bindingssessioncontext_invite(void* ptr, RustBuffer participant, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSSESSIONCONTEXT_INVITE_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSSESSIONCONTEXT_INVITE_ASYNC
uint64_t uniffi_slim_bindings_fn_method_bindingssessioncontext_invite_async(void* ptr, RustBuffer participant
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSSESSIONCONTEXT_IS_INITIATOR
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSSESSIONCONTEXT_IS_INITIATOR
int8_t uniffi_slim_bindings_fn_method_bindingssessioncontext_is_initiator(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSSESSIONCONTEXT_PUBLISH
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSSESSIONCONTEXT_PUBLISH
void uniffi_slim_bindings_fn_method_bindingssessioncontext_publish(void* ptr, RustBuffer data, RustBuffer payload_type, RustBuffer metadata, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSSESSIONCONTEXT_PUBLISH_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSSESSIONCONTEXT_PUBLISH_ASYNC
uint64_t uniffi_slim_bindings_fn_method_bindingssessioncontext_publish_async(void* ptr, RustBuffer data, RustBuffer payload_type, RustBuffer metadata
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSSESSIONCONTEXT_PUBLISH_TO
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSSESSIONCONTEXT_PUBLISH_TO
void uniffi_slim_bindings_fn_method_bindingssessioncontext_publish_to(void* ptr, RustBuffer message_context, RustBuffer data, RustBuffer payload_type, RustBuffer metadata, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSSESSIONCONTEXT_PUBLISH_TO_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSSESSIONCONTEXT_PUBLISH_TO_ASYNC
uint64_t uniffi_slim_bindings_fn_method_bindingssessioncontext_publish_to_async(void* ptr, RustBuffer message_context, RustBuffer data, RustBuffer payload_type, RustBuffer metadata
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSSESSIONCONTEXT_PUBLISH_TO_WITH_COMPLETION
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSSESSIONCONTEXT_PUBLISH_TO_WITH_COMPLETION
void* uniffi_slim_bindings_fn_method_bindingssessioncontext_publish_to_with_completion(void* ptr, RustBuffer message_context, RustBuffer data, RustBuffer payload_type, RustBuffer metadata, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSSESSIONCONTEXT_PUBLISH_TO_WITH_COMPLETION_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSSESSIONCONTEXT_PUBLISH_TO_WITH_COMPLETION_ASYNC
uint64_t uniffi_slim_bindings_fn_method_bindingssessioncontext_publish_to_with_completion_async(void* ptr, RustBuffer message_context, RustBuffer data, RustBuffer payload_type, RustBuffer metadata
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSSESSIONCONTEXT_PUBLISH_WITH_COMPLETION
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSSESSIONCONTEXT_PUBLISH_WITH_COMPLETION
void* uniffi_slim_bindings_fn_method_bindingssessioncontext_publish_with_completion(void* ptr, RustBuffer data, RustBuffer payload_type, RustBuffer metadata, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSSESSIONCONTEXT_PUBLISH_WITH_COMPLETION_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSSESSIONCONTEXT_PUBLISH_WITH_COMPLETION_ASYNC
uint64_t uniffi_slim_bindings_fn_method_bindingssessioncontext_publish_with_completion_async(void* ptr, RustBuffer data, RustBuffer payload_type, RustBuffer metadata
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSSESSIONCONTEXT_PUBLISH_WITH_PARAMS
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSSESSIONCONTEXT_PUBLISH_WITH_PARAMS
void uniffi_slim_bindings_fn_method_bindingssessioncontext_publish_with_params(void* ptr, RustBuffer destination, uint32_t fanout, RustBuffer data, RustBuffer connection_out, RustBuffer payload_type, RustBuffer metadata, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSSESSIONCONTEXT_PUBLISH_WITH_PARAMS_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSSESSIONCONTEXT_PUBLISH_WITH_PARAMS_ASYNC
uint64_t uniffi_slim_bindings_fn_method_bindingssessioncontext_publish_with_params_async(void* ptr, RustBuffer destination, uint32_t fanout, RustBuffer data, RustBuffer connection_out, RustBuffer payload_type, RustBuffer metadata
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSSESSIONCONTEXT_REMOVE
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSSESSIONCONTEXT_REMOVE
void uniffi_slim_bindings_fn_method_bindingssessioncontext_remove(void* ptr, RustBuffer participant, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSSESSIONCONTEXT_REMOVE_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSSESSIONCONTEXT_REMOVE_ASYNC
uint64_t uniffi_slim_bindings_fn_method_bindingssessioncontext_remove_async(void* ptr, RustBuffer participant
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSSESSIONCONTEXT_SESSION_ID
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSSESSIONCONTEXT_SESSION_ID
uint32_t uniffi_slim_bindings_fn_method_bindingssessioncontext_session_id(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSSESSIONCONTEXT_SESSION_TYPE
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSSESSIONCONTEXT_SESSION_TYPE
RustBuffer uniffi_slim_bindings_fn_method_bindingssessioncontext_session_type(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSSESSIONCONTEXT_SOURCE
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_BINDINGSSESSIONCONTEXT_SOURCE
RustBuffer uniffi_slim_bindings_fn_method_bindingssessioncontext_source(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_CLONE_FFICOMPLETIONHANDLE
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_CLONE_FFICOMPLETIONHANDLE
void* uniffi_slim_bindings_fn_clone_fficompletionhandle(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_FREE_FFICOMPLETIONHANDLE
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_FREE_FFICOMPLETIONHANDLE
void uniffi_slim_bindings_fn_free_fficompletionhandle(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_FFICOMPLETIONHANDLE_WAIT
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_FFICOMPLETIONHANDLE_WAIT
void uniffi_slim_bindings_fn_method_fficompletionhandle_wait(void* ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_FFICOMPLETIONHANDLE_WAIT_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_FFICOMPLETIONHANDLE_WAIT_ASYNC
uint64_t uniffi_slim_bindings_fn_method_fficompletionhandle_wait_async(void* ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_FFICOMPLETIONHANDLE_WAIT_FOR
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_FFICOMPLETIONHANDLE_WAIT_FOR
void uniffi_slim_bindings_fn_method_fficompletionhandle_wait_for(void* ptr, RustBuffer timeout, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_FFICOMPLETIONHANDLE_WAIT_FOR_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_METHOD_FFICOMPLETIONHANDLE_WAIT_FOR_ASYNC
uint64_t uniffi_slim_bindings_fn_method_fficompletionhandle_wait_for_async(void* ptr, RustBuffer timeout
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_FUNC_CREATE_APP_WITH_SECRET
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_FUNC_CREATE_APP_WITH_SECRET
void* uniffi_slim_bindings_fn_func_create_app_with_secret(RustBuffer app_name, RustBuffer shared_secret, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_FUNC_GET_BUILD_INFO
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_FUNC_GET_BUILD_INFO
RustBuffer uniffi_slim_bindings_fn_func_get_build_info(RustCallStatus *out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_FUNC_GET_VERSION
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_FUNC_GET_VERSION
RustBuffer uniffi_slim_bindings_fn_func_get_version(RustCallStatus *out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_FUNC_INITIALIZE_CRYPTO_PROVIDER
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_FN_FUNC_INITIALIZE_CRYPTO_PROVIDER
void uniffi_slim_bindings_fn_func_initialize_crypto_provider(RustCallStatus *out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUSTBUFFER_ALLOC
RustBuffer ffi_slim_bindings_rustbuffer_alloc(uint64_t size, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_slim_bindings_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUSTBUFFER_FREE
void ffi_slim_bindings_rustbuffer_free(RustBuffer buf, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUSTBUFFER_RESERVE
RustBuffer ffi_slim_bindings_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_POLL_U8
void ffi_slim_bindings_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_CANCEL_U8
void ffi_slim_bindings_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_FREE_U8
void ffi_slim_bindings_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_slim_bindings_rust_future_complete_u8(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_POLL_I8
void ffi_slim_bindings_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_CANCEL_I8
void ffi_slim_bindings_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_FREE_I8
void ffi_slim_bindings_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_COMPLETE_I8
int8_t ffi_slim_bindings_rust_future_complete_i8(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_POLL_U16
void ffi_slim_bindings_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_CANCEL_U16
void ffi_slim_bindings_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_FREE_U16
void ffi_slim_bindings_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_slim_bindings_rust_future_complete_u16(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_POLL_I16
void ffi_slim_bindings_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_CANCEL_I16
void ffi_slim_bindings_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_FREE_I16
void ffi_slim_bindings_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_COMPLETE_I16
int16_t ffi_slim_bindings_rust_future_complete_i16(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_POLL_U32
void ffi_slim_bindings_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_CANCEL_U32
void ffi_slim_bindings_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_FREE_U32
void ffi_slim_bindings_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_slim_bindings_rust_future_complete_u32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_POLL_I32
void ffi_slim_bindings_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_CANCEL_I32
void ffi_slim_bindings_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_FREE_I32
void ffi_slim_bindings_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_COMPLETE_I32
int32_t ffi_slim_bindings_rust_future_complete_i32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_POLL_U64
void ffi_slim_bindings_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_CANCEL_U64
void ffi_slim_bindings_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_FREE_U64
void ffi_slim_bindings_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_slim_bindings_rust_future_complete_u64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_POLL_I64
void ffi_slim_bindings_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_CANCEL_I64
void ffi_slim_bindings_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_FREE_I64
void ffi_slim_bindings_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_COMPLETE_I64
int64_t ffi_slim_bindings_rust_future_complete_i64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_POLL_F32
void ffi_slim_bindings_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_CANCEL_F32
void ffi_slim_bindings_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_FREE_F32
void ffi_slim_bindings_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_COMPLETE_F32
float ffi_slim_bindings_rust_future_complete_f32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_POLL_F64
void ffi_slim_bindings_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_CANCEL_F64
void ffi_slim_bindings_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_FREE_F64
void ffi_slim_bindings_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_COMPLETE_F64
double ffi_slim_bindings_rust_future_complete_f64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_POLL_POINTER
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_POLL_POINTER
void ffi_slim_bindings_rust_future_poll_pointer(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_CANCEL_POINTER
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_CANCEL_POINTER
void ffi_slim_bindings_rust_future_cancel_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_FREE_POINTER
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_FREE_POINTER
void ffi_slim_bindings_rust_future_free_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_COMPLETE_POINTER
void* ffi_slim_bindings_rust_future_complete_pointer(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_slim_bindings_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_slim_bindings_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_slim_bindings_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_slim_bindings_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_POLL_VOID
void ffi_slim_bindings_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_CANCEL_VOID
void ffi_slim_bindings_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_FREE_VOID
void ffi_slim_bindings_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_RUST_FUTURE_COMPLETE_VOID
void ffi_slim_bindings_rust_future_complete_void(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_FUNC_CREATE_APP_WITH_SECRET
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_FUNC_CREATE_APP_WITH_SECRET
uint16_t uniffi_slim_bindings_checksum_func_create_app_with_secret(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_FUNC_GET_BUILD_INFO
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_FUNC_GET_BUILD_INFO
uint16_t uniffi_slim_bindings_checksum_func_get_build_info(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_FUNC_GET_VERSION
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_FUNC_GET_VERSION
uint16_t uniffi_slim_bindings_checksum_func_get_version(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_FUNC_INITIALIZE_CRYPTO_PROVIDER
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_FUNC_INITIALIZE_CRYPTO_PROVIDER
uint16_t uniffi_slim_bindings_checksum_func_initialize_crypto_provider(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSADAPTER_CONNECT
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSADAPTER_CONNECT
uint16_t uniffi_slim_bindings_checksum_method_bindingsadapter_connect(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSADAPTER_CONNECT_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSADAPTER_CONNECT_ASYNC
uint16_t uniffi_slim_bindings_checksum_method_bindingsadapter_connect_async(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSADAPTER_CREATE_SESSION
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSADAPTER_CREATE_SESSION
uint16_t uniffi_slim_bindings_checksum_method_bindingsadapter_create_session(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSADAPTER_CREATE_SESSION_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSADAPTER_CREATE_SESSION_ASYNC
uint16_t uniffi_slim_bindings_checksum_method_bindingsadapter_create_session_async(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSADAPTER_DELETE_SESSION
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSADAPTER_DELETE_SESSION
uint16_t uniffi_slim_bindings_checksum_method_bindingsadapter_delete_session(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSADAPTER_DELETE_SESSION_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSADAPTER_DELETE_SESSION_ASYNC
uint16_t uniffi_slim_bindings_checksum_method_bindingsadapter_delete_session_async(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSADAPTER_DISCONNECT
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSADAPTER_DISCONNECT
uint16_t uniffi_slim_bindings_checksum_method_bindingsadapter_disconnect(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSADAPTER_DISCONNECT_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSADAPTER_DISCONNECT_ASYNC
uint16_t uniffi_slim_bindings_checksum_method_bindingsadapter_disconnect_async(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSADAPTER_ID
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSADAPTER_ID
uint16_t uniffi_slim_bindings_checksum_method_bindingsadapter_id(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSADAPTER_LISTEN_FOR_SESSION
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSADAPTER_LISTEN_FOR_SESSION
uint16_t uniffi_slim_bindings_checksum_method_bindingsadapter_listen_for_session(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSADAPTER_LISTEN_FOR_SESSION_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSADAPTER_LISTEN_FOR_SESSION_ASYNC
uint16_t uniffi_slim_bindings_checksum_method_bindingsadapter_listen_for_session_async(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSADAPTER_NAME
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSADAPTER_NAME
uint16_t uniffi_slim_bindings_checksum_method_bindingsadapter_name(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSADAPTER_REMOVE_ROUTE
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSADAPTER_REMOVE_ROUTE
uint16_t uniffi_slim_bindings_checksum_method_bindingsadapter_remove_route(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSADAPTER_REMOVE_ROUTE_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSADAPTER_REMOVE_ROUTE_ASYNC
uint16_t uniffi_slim_bindings_checksum_method_bindingsadapter_remove_route_async(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSADAPTER_RUN_SERVER
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSADAPTER_RUN_SERVER
uint16_t uniffi_slim_bindings_checksum_method_bindingsadapter_run_server(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSADAPTER_RUN_SERVER_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSADAPTER_RUN_SERVER_ASYNC
uint16_t uniffi_slim_bindings_checksum_method_bindingsadapter_run_server_async(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSADAPTER_SET_ROUTE
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSADAPTER_SET_ROUTE
uint16_t uniffi_slim_bindings_checksum_method_bindingsadapter_set_route(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSADAPTER_SET_ROUTE_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSADAPTER_SET_ROUTE_ASYNC
uint16_t uniffi_slim_bindings_checksum_method_bindingsadapter_set_route_async(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSADAPTER_STOP_SERVER
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSADAPTER_STOP_SERVER
uint16_t uniffi_slim_bindings_checksum_method_bindingsadapter_stop_server(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSADAPTER_SUBSCRIBE
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSADAPTER_SUBSCRIBE
uint16_t uniffi_slim_bindings_checksum_method_bindingsadapter_subscribe(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSADAPTER_SUBSCRIBE_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSADAPTER_SUBSCRIBE_ASYNC
uint16_t uniffi_slim_bindings_checksum_method_bindingsadapter_subscribe_async(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSADAPTER_UNSUBSCRIBE
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSADAPTER_UNSUBSCRIBE
uint16_t uniffi_slim_bindings_checksum_method_bindingsadapter_unsubscribe(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSADAPTER_UNSUBSCRIBE_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSADAPTER_UNSUBSCRIBE_ASYNC
uint16_t uniffi_slim_bindings_checksum_method_bindingsadapter_unsubscribe_async(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSSESSIONCONTEXT_DESTINATION
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSSESSIONCONTEXT_DESTINATION
uint16_t uniffi_slim_bindings_checksum_method_bindingssessioncontext_destination(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSSESSIONCONTEXT_GET_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSSESSIONCONTEXT_GET_MESSAGE
uint16_t uniffi_slim_bindings_checksum_method_bindingssessioncontext_get_message(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSSESSIONCONTEXT_GET_MESSAGE_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSSESSIONCONTEXT_GET_MESSAGE_ASYNC
uint16_t uniffi_slim_bindings_checksum_method_bindingssessioncontext_get_message_async(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSSESSIONCONTEXT_INVITE
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSSESSIONCONTEXT_INVITE
uint16_t uniffi_slim_bindings_checksum_method_bindingssessioncontext_invite(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSSESSIONCONTEXT_INVITE_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSSESSIONCONTEXT_INVITE_ASYNC
uint16_t uniffi_slim_bindings_checksum_method_bindingssessioncontext_invite_async(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSSESSIONCONTEXT_IS_INITIATOR
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSSESSIONCONTEXT_IS_INITIATOR
uint16_t uniffi_slim_bindings_checksum_method_bindingssessioncontext_is_initiator(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSSESSIONCONTEXT_PUBLISH
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSSESSIONCONTEXT_PUBLISH
uint16_t uniffi_slim_bindings_checksum_method_bindingssessioncontext_publish(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSSESSIONCONTEXT_PUBLISH_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSSESSIONCONTEXT_PUBLISH_ASYNC
uint16_t uniffi_slim_bindings_checksum_method_bindingssessioncontext_publish_async(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSSESSIONCONTEXT_PUBLISH_TO
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSSESSIONCONTEXT_PUBLISH_TO
uint16_t uniffi_slim_bindings_checksum_method_bindingssessioncontext_publish_to(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSSESSIONCONTEXT_PUBLISH_TO_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSSESSIONCONTEXT_PUBLISH_TO_ASYNC
uint16_t uniffi_slim_bindings_checksum_method_bindingssessioncontext_publish_to_async(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSSESSIONCONTEXT_PUBLISH_TO_WITH_COMPLETION
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSSESSIONCONTEXT_PUBLISH_TO_WITH_COMPLETION
uint16_t uniffi_slim_bindings_checksum_method_bindingssessioncontext_publish_to_with_completion(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSSESSIONCONTEXT_PUBLISH_TO_WITH_COMPLETION_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSSESSIONCONTEXT_PUBLISH_TO_WITH_COMPLETION_ASYNC
uint16_t uniffi_slim_bindings_checksum_method_bindingssessioncontext_publish_to_with_completion_async(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSSESSIONCONTEXT_PUBLISH_WITH_COMPLETION
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSSESSIONCONTEXT_PUBLISH_WITH_COMPLETION
uint16_t uniffi_slim_bindings_checksum_method_bindingssessioncontext_publish_with_completion(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSSESSIONCONTEXT_PUBLISH_WITH_COMPLETION_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSSESSIONCONTEXT_PUBLISH_WITH_COMPLETION_ASYNC
uint16_t uniffi_slim_bindings_checksum_method_bindingssessioncontext_publish_with_completion_async(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSSESSIONCONTEXT_PUBLISH_WITH_PARAMS
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSSESSIONCONTEXT_PUBLISH_WITH_PARAMS
uint16_t uniffi_slim_bindings_checksum_method_bindingssessioncontext_publish_with_params(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSSESSIONCONTEXT_PUBLISH_WITH_PARAMS_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSSESSIONCONTEXT_PUBLISH_WITH_PARAMS_ASYNC
uint16_t uniffi_slim_bindings_checksum_method_bindingssessioncontext_publish_with_params_async(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSSESSIONCONTEXT_REMOVE
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSSESSIONCONTEXT_REMOVE
uint16_t uniffi_slim_bindings_checksum_method_bindingssessioncontext_remove(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSSESSIONCONTEXT_REMOVE_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSSESSIONCONTEXT_REMOVE_ASYNC
uint16_t uniffi_slim_bindings_checksum_method_bindingssessioncontext_remove_async(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSSESSIONCONTEXT_SESSION_ID
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSSESSIONCONTEXT_SESSION_ID
uint16_t uniffi_slim_bindings_checksum_method_bindingssessioncontext_session_id(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSSESSIONCONTEXT_SESSION_TYPE
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSSESSIONCONTEXT_SESSION_TYPE
uint16_t uniffi_slim_bindings_checksum_method_bindingssessioncontext_session_type(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSSESSIONCONTEXT_SOURCE
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_BINDINGSSESSIONCONTEXT_SOURCE
uint16_t uniffi_slim_bindings_checksum_method_bindingssessioncontext_source(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_FFICOMPLETIONHANDLE_WAIT
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_FFICOMPLETIONHANDLE_WAIT
uint16_t uniffi_slim_bindings_checksum_method_fficompletionhandle_wait(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_FFICOMPLETIONHANDLE_WAIT_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_FFICOMPLETIONHANDLE_WAIT_ASYNC
uint16_t uniffi_slim_bindings_checksum_method_fficompletionhandle_wait_async(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_FFICOMPLETIONHANDLE_WAIT_FOR
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_FFICOMPLETIONHANDLE_WAIT_FOR
uint16_t uniffi_slim_bindings_checksum_method_fficompletionhandle_wait_for(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_FFICOMPLETIONHANDLE_WAIT_FOR_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_BINDINGS_CHECKSUM_METHOD_FFICOMPLETIONHANDLE_WAIT_FOR_ASYNC
uint16_t uniffi_slim_bindings_checksum_method_fficompletionhandle_wait_for_async(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_SLIM_BINDINGS_UNIFFI_CONTRACT_VERSION
uint32_t ffi_slim_bindings_uniffi_contract_version(void
    
);
#endif


#ifdef _WIN32
__declspec(dllexport) void slim_bindings_uniffiFutureContinuationCallback(uint64_t, int8_t);
__declspec(dllexport) void slim_bindings_uniffiFreeGorutine(uint64_t);
#else
void slim_bindings_uniffiFutureContinuationCallback(uint64_t, int8_t);
void slim_bindings_uniffiFreeGorutine(uint64_t);
#endif
