

// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!



#include <stdbool.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
	// We also try to prevent mixing versions of shared uniffi header structs.
	// If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V6
	#ifndef UNIFFI_SHARED_HEADER_V6
		#error Combining helper code from multiple versions of uniffi is not supported
	#endif // ndef UNIFFI_SHARED_HEADER_V6
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V6
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V6 in this file.           ⚠️

typedef struct RustBuffer {
	uint64_t capacity;
	uint64_t len;
	uint8_t *data;
} RustBuffer;

typedef struct ForeignBytes {
	int32_t len;
	const uint8_t *data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
	int8_t code;
	RustBuffer errorBuf;
} RustCallStatus;

#endif // UNIFFI_SHARED_H


#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t data, int8_t poll_result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiRustFutureContinuationCallback(
				UniffiRustFutureContinuationCallback cb, uint64_t data, int8_t poll_result)
{
	return cb(data, poll_result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
typedef void (*UniffiForeignFutureDroppedCallback)(uint64_t handle);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureDroppedCallback(
				UniffiForeignFutureDroppedCallback cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t handle);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceFree(
				UniffiCallbackInterfaceFree cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
typedef uint64_t (*UniffiCallbackInterfaceClone)(uint64_t handle);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static uint64_t call_UniffiCallbackInterfaceClone(
				UniffiCallbackInterfaceClone cb, uint64_t handle)
{
	return cb(handle);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
typedef struct UniffiForeignFutureDroppedCallbackStruct {
    uint64_t handle;
    UniffiForeignFutureDroppedCallback free;
} UniffiForeignFutureDroppedCallbackStruct;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
typedef struct UniffiForeignFutureResultU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t callback_data, UniffiForeignFutureResultU8 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU8(
				UniffiForeignFutureCompleteU8 cb, uint64_t callback_data, UniffiForeignFutureResultU8 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
typedef struct UniffiForeignFutureResultI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t callback_data, UniffiForeignFutureResultI8 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI8(
				UniffiForeignFutureCompleteI8 cb, uint64_t callback_data, UniffiForeignFutureResultI8 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
typedef struct UniffiForeignFutureResultU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t callback_data, UniffiForeignFutureResultU16 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU16(
				UniffiForeignFutureCompleteU16 cb, uint64_t callback_data, UniffiForeignFutureResultU16 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
typedef struct UniffiForeignFutureResultI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t callback_data, UniffiForeignFutureResultI16 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI16(
				UniffiForeignFutureCompleteI16 cb, uint64_t callback_data, UniffiForeignFutureResultI16 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
typedef struct UniffiForeignFutureResultU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t callback_data, UniffiForeignFutureResultU32 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU32(
				UniffiForeignFutureCompleteU32 cb, uint64_t callback_data, UniffiForeignFutureResultU32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
typedef struct UniffiForeignFutureResultI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t callback_data, UniffiForeignFutureResultI32 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI32(
				UniffiForeignFutureCompleteI32 cb, uint64_t callback_data, UniffiForeignFutureResultI32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
typedef struct UniffiForeignFutureResultU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t callback_data, UniffiForeignFutureResultU64 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteU64(
				UniffiForeignFutureCompleteU64 cb, uint64_t callback_data, UniffiForeignFutureResultU64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
typedef struct UniffiForeignFutureResultI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t callback_data, UniffiForeignFutureResultI64 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteI64(
				UniffiForeignFutureCompleteI64 cb, uint64_t callback_data, UniffiForeignFutureResultI64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
typedef struct UniffiForeignFutureResultF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t callback_data, UniffiForeignFutureResultF32 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteF32(
				UniffiForeignFutureCompleteF32 cb, uint64_t callback_data, UniffiForeignFutureResultF32 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
typedef struct UniffiForeignFutureResultF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t callback_data, UniffiForeignFutureResultF64 result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteF64(
				UniffiForeignFutureCompleteF64 cb, uint64_t callback_data, UniffiForeignFutureResultF64 result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
typedef struct UniffiForeignFutureResultRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t callback_data, UniffiForeignFutureResultRustBuffer result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteRustBuffer(
				UniffiForeignFutureCompleteRustBuffer cb, uint64_t callback_data, UniffiForeignFutureResultRustBuffer result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
typedef struct UniffiForeignFutureResultVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureResultVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t callback_data, UniffiForeignFutureResultVoid result);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiForeignFutureCompleteVoid(
				UniffiForeignFutureCompleteVoid cb, uint64_t callback_data, UniffiForeignFutureResultVoid result)
{
	return cb(callback_data, result);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_STREAM_STREAM_HANDLER_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_STREAM_STREAM_HANDLER_METHOD0
typedef void (*UniffiCallbackInterfaceStreamStreamHandlerMethod0)(uint64_t uniffi_handle, uint64_t stream, uint64_t context, uint64_t sink, UniffiForeignFutureCompleteVoid uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFutureDroppedCallbackStruct* uniffi_out_dropped_callback);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceStreamStreamHandlerMethod0(
				UniffiCallbackInterfaceStreamStreamHandlerMethod0 cb, uint64_t uniffi_handle, uint64_t stream, uint64_t context, uint64_t sink, UniffiForeignFutureCompleteVoid uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFutureDroppedCallbackStruct* uniffi_out_dropped_callback)
{
	return cb(uniffi_handle, stream, context, sink, uniffi_future_callback, uniffi_callback_data, uniffi_out_dropped_callback);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_STREAM_UNARY_HANDLER_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_STREAM_UNARY_HANDLER_METHOD0
typedef void (*UniffiCallbackInterfaceStreamUnaryHandlerMethod0)(uint64_t uniffi_handle, uint64_t stream, uint64_t context, UniffiForeignFutureCompleteRustBuffer uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFutureDroppedCallbackStruct* uniffi_out_dropped_callback);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceStreamUnaryHandlerMethod0(
				UniffiCallbackInterfaceStreamUnaryHandlerMethod0 cb, uint64_t uniffi_handle, uint64_t stream, uint64_t context, UniffiForeignFutureCompleteRustBuffer uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFutureDroppedCallbackStruct* uniffi_out_dropped_callback)
{
	return cb(uniffi_handle, stream, context, uniffi_future_callback, uniffi_callback_data, uniffi_out_dropped_callback);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_UNARY_STREAM_HANDLER_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_UNARY_STREAM_HANDLER_METHOD0
typedef void (*UniffiCallbackInterfaceUnaryStreamHandlerMethod0)(uint64_t uniffi_handle, RustBuffer request, uint64_t context, uint64_t sink, UniffiForeignFutureCompleteVoid uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFutureDroppedCallbackStruct* uniffi_out_dropped_callback);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceUnaryStreamHandlerMethod0(
				UniffiCallbackInterfaceUnaryStreamHandlerMethod0 cb, uint64_t uniffi_handle, RustBuffer request, uint64_t context, uint64_t sink, UniffiForeignFutureCompleteVoid uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFutureDroppedCallbackStruct* uniffi_out_dropped_callback)
{
	return cb(uniffi_handle, request, context, sink, uniffi_future_callback, uniffi_callback_data, uniffi_out_dropped_callback);
}


#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_UNARY_UNARY_HANDLER_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_UNARY_UNARY_HANDLER_METHOD0
typedef void (*UniffiCallbackInterfaceUnaryUnaryHandlerMethod0)(uint64_t uniffi_handle, RustBuffer request, uint64_t context, UniffiForeignFutureCompleteRustBuffer uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFutureDroppedCallbackStruct* uniffi_out_dropped_callback);

// Making function static workaround:
// https://github.com/golang/go/issues/11263
static void call_UniffiCallbackInterfaceUnaryUnaryHandlerMethod0(
				UniffiCallbackInterfaceUnaryUnaryHandlerMethod0 cb, uint64_t uniffi_handle, RustBuffer request, uint64_t context, UniffiForeignFutureCompleteRustBuffer uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFutureDroppedCallbackStruct* uniffi_out_dropped_callback)
{
	return cb(uniffi_handle, request, context, uniffi_future_callback, uniffi_callback_data, uniffi_out_dropped_callback);
}


#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_STREAM_STREAM_HANDLER
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_STREAM_STREAM_HANDLER
typedef struct UniffiVTableCallbackInterfaceStreamStreamHandler {
    UniffiCallbackInterfaceFree uniffiFree;
    UniffiCallbackInterfaceClone uniffiClone;
    UniffiCallbackInterfaceStreamStreamHandlerMethod0 handle;
} UniffiVTableCallbackInterfaceStreamStreamHandler;

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_STREAM_UNARY_HANDLER
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_STREAM_UNARY_HANDLER
typedef struct UniffiVTableCallbackInterfaceStreamUnaryHandler {
    UniffiCallbackInterfaceFree uniffiFree;
    UniffiCallbackInterfaceClone uniffiClone;
    UniffiCallbackInterfaceStreamUnaryHandlerMethod0 handle;
} UniffiVTableCallbackInterfaceStreamUnaryHandler;

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_UNARY_STREAM_HANDLER
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_UNARY_STREAM_HANDLER
typedef struct UniffiVTableCallbackInterfaceUnaryStreamHandler {
    UniffiCallbackInterfaceFree uniffiFree;
    UniffiCallbackInterfaceClone uniffiClone;
    UniffiCallbackInterfaceUnaryStreamHandlerMethod0 handle;
} UniffiVTableCallbackInterfaceUnaryStreamHandler;

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_UNARY_UNARY_HANDLER
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_UNARY_UNARY_HANDLER
typedef struct UniffiVTableCallbackInterfaceUnaryUnaryHandler {
    UniffiCallbackInterfaceFree uniffiFree;
    UniffiCallbackInterfaceClone uniffiClone;
    UniffiCallbackInterfaceUnaryUnaryHandlerMethod0 handle;
} UniffiVTableCallbackInterfaceUnaryUnaryHandler;

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_CLONE_CHANNEL
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_CLONE_CHANNEL
uint64_t uniffi_slim_rpc_fn_clone_channel(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_FREE_CHANNEL
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_FREE_CHANNEL
void uniffi_slim_rpc_fn_free_channel(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_CONSTRUCTOR_CHANNEL_NEW
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_CONSTRUCTOR_CHANNEL_NEW
uint64_t uniffi_slim_rpc_fn_constructor_channel_new(uint64_t app, uint64_t remote, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_CONSTRUCTOR_CHANNEL_NEW_GROUP
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_CONSTRUCTOR_CHANNEL_NEW_GROUP
uint64_t uniffi_slim_rpc_fn_constructor_channel_new_group(uint64_t app, RustBuffer members, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_CONSTRUCTOR_CHANNEL_NEW_GROUP_WITH_CONNECTION
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_CONSTRUCTOR_CHANNEL_NEW_GROUP_WITH_CONNECTION
uint64_t uniffi_slim_rpc_fn_constructor_channel_new_group_with_connection(uint64_t app, RustBuffer members, RustBuffer connection_id, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_CONSTRUCTOR_CHANNEL_NEW_WITH_CONNECTION
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_CONSTRUCTOR_CHANNEL_NEW_WITH_CONNECTION
uint64_t uniffi_slim_rpc_fn_constructor_channel_new_with_connection(uint64_t app, uint64_t remote, RustBuffer connection_id, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_CHANNEL_CALL_MULTICAST_STREAM_STREAM
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_CHANNEL_CALL_MULTICAST_STREAM_STREAM
uint64_t uniffi_slim_rpc_fn_method_channel_call_multicast_stream_stream(uint64_t ptr, RustBuffer service_name, RustBuffer method_name, RustBuffer timeout, RustBuffer metadata, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_CHANNEL_CALL_MULTICAST_STREAM_UNARY
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_CHANNEL_CALL_MULTICAST_STREAM_UNARY
uint64_t uniffi_slim_rpc_fn_method_channel_call_multicast_stream_unary(uint64_t ptr, RustBuffer service_name, RustBuffer method_name, RustBuffer timeout, RustBuffer metadata, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_CHANNEL_CALL_MULTICAST_UNARY
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_CHANNEL_CALL_MULTICAST_UNARY
uint64_t uniffi_slim_rpc_fn_method_channel_call_multicast_unary(uint64_t ptr, RustBuffer service_name, RustBuffer method_name, RustBuffer request, RustBuffer timeout, RustBuffer metadata, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_CHANNEL_CALL_MULTICAST_UNARY_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_CHANNEL_CALL_MULTICAST_UNARY_ASYNC
uint64_t uniffi_slim_rpc_fn_method_channel_call_multicast_unary_async(uint64_t ptr, RustBuffer service_name, RustBuffer method_name, RustBuffer request, RustBuffer timeout, RustBuffer metadata
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_CHANNEL_CALL_MULTICAST_UNARY_STREAM
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_CHANNEL_CALL_MULTICAST_UNARY_STREAM
uint64_t uniffi_slim_rpc_fn_method_channel_call_multicast_unary_stream(uint64_t ptr, RustBuffer service_name, RustBuffer method_name, RustBuffer request, RustBuffer timeout, RustBuffer metadata, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_CHANNEL_CALL_MULTICAST_UNARY_STREAM_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_CHANNEL_CALL_MULTICAST_UNARY_STREAM_ASYNC
uint64_t uniffi_slim_rpc_fn_method_channel_call_multicast_unary_stream_async(uint64_t ptr, RustBuffer service_name, RustBuffer method_name, RustBuffer request, RustBuffer timeout, RustBuffer metadata
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_CHANNEL_CALL_STREAM_STREAM
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_CHANNEL_CALL_STREAM_STREAM
uint64_t uniffi_slim_rpc_fn_method_channel_call_stream_stream(uint64_t ptr, RustBuffer service_name, RustBuffer method_name, RustBuffer timeout, RustBuffer metadata, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_CHANNEL_CALL_STREAM_UNARY
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_CHANNEL_CALL_STREAM_UNARY
uint64_t uniffi_slim_rpc_fn_method_channel_call_stream_unary(uint64_t ptr, RustBuffer service_name, RustBuffer method_name, RustBuffer timeout, RustBuffer metadata, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_CHANNEL_CALL_UNARY
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_CHANNEL_CALL_UNARY
RustBuffer uniffi_slim_rpc_fn_method_channel_call_unary(uint64_t ptr, RustBuffer service_name, RustBuffer method_name, RustBuffer request, RustBuffer timeout, RustBuffer metadata, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_CHANNEL_CALL_UNARY_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_CHANNEL_CALL_UNARY_ASYNC
uint64_t uniffi_slim_rpc_fn_method_channel_call_unary_async(uint64_t ptr, RustBuffer service_name, RustBuffer method_name, RustBuffer request, RustBuffer timeout, RustBuffer metadata
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_CHANNEL_CALL_UNARY_STREAM
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_CHANNEL_CALL_UNARY_STREAM
uint64_t uniffi_slim_rpc_fn_method_channel_call_unary_stream(uint64_t ptr, RustBuffer service_name, RustBuffer method_name, RustBuffer request, RustBuffer timeout, RustBuffer metadata, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_CHANNEL_CALL_UNARY_STREAM_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_CHANNEL_CALL_UNARY_STREAM_ASYNC
uint64_t uniffi_slim_rpc_fn_method_channel_call_unary_stream_async(uint64_t ptr, RustBuffer service_name, RustBuffer method_name, RustBuffer request, RustBuffer timeout, RustBuffer metadata
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_CHANNEL_CLOSE_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_CHANNEL_CLOSE_ASYNC
uint64_t uniffi_slim_rpc_fn_method_channel_close_async(uint64_t ptr, RustBuffer timeout
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_CHANNEL_CLOSE_BLOCKING
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_CHANNEL_CLOSE_BLOCKING
void uniffi_slim_rpc_fn_method_channel_close_blocking(uint64_t ptr, RustBuffer timeout, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_CLONE_CONTEXT
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_CLONE_CONTEXT
uint64_t uniffi_slim_rpc_fn_clone_context(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_FREE_CONTEXT
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_FREE_CONTEXT
void uniffi_slim_rpc_fn_free_context(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_CONTEXT_DEADLINE
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_CONTEXT_DEADLINE
RustBuffer uniffi_slim_rpc_fn_method_context_deadline(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_CONTEXT_IS_DEADLINE_EXCEEDED
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_CONTEXT_IS_DEADLINE_EXCEEDED
int8_t uniffi_slim_rpc_fn_method_context_is_deadline_exceeded(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_CONTEXT_METADATA
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_CONTEXT_METADATA
RustBuffer uniffi_slim_rpc_fn_method_context_metadata(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_CONTEXT_REMAINING_TIME
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_CONTEXT_REMAINING_TIME
RustBuffer uniffi_slim_rpc_fn_method_context_remaining_time(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_CONTEXT_SESSION_ID
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_CONTEXT_SESSION_ID
RustBuffer uniffi_slim_rpc_fn_method_context_session_id(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_CLONE_STREAMSTREAMHANDLER
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_CLONE_STREAMSTREAMHANDLER
uint64_t uniffi_slim_rpc_fn_clone_streamstreamhandler(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_FREE_STREAMSTREAMHANDLER
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_FREE_STREAMSTREAMHANDLER
void uniffi_slim_rpc_fn_free_streamstreamhandler(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_INIT_CALLBACK_VTABLE_STREAMSTREAMHANDLER
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_INIT_CALLBACK_VTABLE_STREAMSTREAMHANDLER
void uniffi_slim_rpc_fn_init_callback_vtable_streamstreamhandler(UniffiVTableCallbackInterfaceStreamStreamHandler* vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_STREAMSTREAMHANDLER_HANDLE
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_STREAMSTREAMHANDLER_HANDLE
uint64_t uniffi_slim_rpc_fn_method_streamstreamhandler_handle(uint64_t ptr, uint64_t stream, uint64_t context, uint64_t sink
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_CLONE_STREAMUNARYHANDLER
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_CLONE_STREAMUNARYHANDLER
uint64_t uniffi_slim_rpc_fn_clone_streamunaryhandler(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_FREE_STREAMUNARYHANDLER
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_FREE_STREAMUNARYHANDLER
void uniffi_slim_rpc_fn_free_streamunaryhandler(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_INIT_CALLBACK_VTABLE_STREAMUNARYHANDLER
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_INIT_CALLBACK_VTABLE_STREAMUNARYHANDLER
void uniffi_slim_rpc_fn_init_callback_vtable_streamunaryhandler(UniffiVTableCallbackInterfaceStreamUnaryHandler* vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_STREAMUNARYHANDLER_HANDLE
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_STREAMUNARYHANDLER_HANDLE
uint64_t uniffi_slim_rpc_fn_method_streamunaryhandler_handle(uint64_t ptr, uint64_t stream, uint64_t context
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_CLONE_UNARYSTREAMHANDLER
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_CLONE_UNARYSTREAMHANDLER
uint64_t uniffi_slim_rpc_fn_clone_unarystreamhandler(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_FREE_UNARYSTREAMHANDLER
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_FREE_UNARYSTREAMHANDLER
void uniffi_slim_rpc_fn_free_unarystreamhandler(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_INIT_CALLBACK_VTABLE_UNARYSTREAMHANDLER
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_INIT_CALLBACK_VTABLE_UNARYSTREAMHANDLER
void uniffi_slim_rpc_fn_init_callback_vtable_unarystreamhandler(UniffiVTableCallbackInterfaceUnaryStreamHandler* vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_UNARYSTREAMHANDLER_HANDLE
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_UNARYSTREAMHANDLER_HANDLE
uint64_t uniffi_slim_rpc_fn_method_unarystreamhandler_handle(uint64_t ptr, RustBuffer request, uint64_t context, uint64_t sink
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_CLONE_UNARYUNARYHANDLER
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_CLONE_UNARYUNARYHANDLER
uint64_t uniffi_slim_rpc_fn_clone_unaryunaryhandler(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_FREE_UNARYUNARYHANDLER
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_FREE_UNARYUNARYHANDLER
void uniffi_slim_rpc_fn_free_unaryunaryhandler(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_INIT_CALLBACK_VTABLE_UNARYUNARYHANDLER
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_INIT_CALLBACK_VTABLE_UNARYUNARYHANDLER
void uniffi_slim_rpc_fn_init_callback_vtable_unaryunaryhandler(UniffiVTableCallbackInterfaceUnaryUnaryHandler* vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_UNARYUNARYHANDLER_HANDLE
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_UNARYUNARYHANDLER_HANDLE
uint64_t uniffi_slim_rpc_fn_method_unaryunaryhandler_handle(uint64_t ptr, RustBuffer request, uint64_t context
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_CLONE_SERVER
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_CLONE_SERVER
uint64_t uniffi_slim_rpc_fn_clone_server(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_FREE_SERVER
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_FREE_SERVER
void uniffi_slim_rpc_fn_free_server(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_CONSTRUCTOR_SERVER_NEW
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_CONSTRUCTOR_SERVER_NEW
uint64_t uniffi_slim_rpc_fn_constructor_server_new(uint64_t app, uint64_t base_name, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_CONSTRUCTOR_SERVER_NEW_WITH_CONNECTION
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_CONSTRUCTOR_SERVER_NEW_WITH_CONNECTION
uint64_t uniffi_slim_rpc_fn_constructor_server_new_with_connection(uint64_t app, uint64_t base_name, RustBuffer connection_id, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_SERVER_REGISTER_STREAM_STREAM
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_SERVER_REGISTER_STREAM_STREAM
void uniffi_slim_rpc_fn_method_server_register_stream_stream(uint64_t ptr, RustBuffer service_name, RustBuffer method_name, uint64_t handler, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_SERVER_REGISTER_STREAM_UNARY
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_SERVER_REGISTER_STREAM_UNARY
void uniffi_slim_rpc_fn_method_server_register_stream_unary(uint64_t ptr, RustBuffer service_name, RustBuffer method_name, uint64_t handler, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_SERVER_REGISTER_UNARY_STREAM
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_SERVER_REGISTER_UNARY_STREAM
void uniffi_slim_rpc_fn_method_server_register_unary_stream(uint64_t ptr, RustBuffer service_name, RustBuffer method_name, uint64_t handler, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_SERVER_REGISTER_UNARY_UNARY
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_SERVER_REGISTER_UNARY_UNARY
void uniffi_slim_rpc_fn_method_server_register_unary_unary(uint64_t ptr, RustBuffer service_name, RustBuffer method_name, uint64_t handler, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_SERVER_SERVE_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_SERVER_SERVE_ASYNC
uint64_t uniffi_slim_rpc_fn_method_server_serve_async(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_SERVER_SERVE_BLOCKING
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_SERVER_SERVE_BLOCKING
void uniffi_slim_rpc_fn_method_server_serve_blocking(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_SERVER_SHUTDOWN_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_SERVER_SHUTDOWN_ASYNC
uint64_t uniffi_slim_rpc_fn_method_server_shutdown_async(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_SERVER_SHUTDOWN_BLOCKING
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_SERVER_SHUTDOWN_BLOCKING
void uniffi_slim_rpc_fn_method_server_shutdown_blocking(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_CLONE_BIDISTREAMHANDLER
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_CLONE_BIDISTREAMHANDLER
uint64_t uniffi_slim_rpc_fn_clone_bidistreamhandler(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_FREE_BIDISTREAMHANDLER
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_FREE_BIDISTREAMHANDLER
void uniffi_slim_rpc_fn_free_bidistreamhandler(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_BIDISTREAMHANDLER_CLOSE_SEND
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_BIDISTREAMHANDLER_CLOSE_SEND
void uniffi_slim_rpc_fn_method_bidistreamhandler_close_send(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_BIDISTREAMHANDLER_CLOSE_SEND_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_BIDISTREAMHANDLER_CLOSE_SEND_ASYNC
uint64_t uniffi_slim_rpc_fn_method_bidistreamhandler_close_send_async(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_BIDISTREAMHANDLER_RECV
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_BIDISTREAMHANDLER_RECV
RustBuffer uniffi_slim_rpc_fn_method_bidistreamhandler_recv(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_BIDISTREAMHANDLER_RECV_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_BIDISTREAMHANDLER_RECV_ASYNC
uint64_t uniffi_slim_rpc_fn_method_bidistreamhandler_recv_async(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_BIDISTREAMHANDLER_SEND
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_BIDISTREAMHANDLER_SEND
void uniffi_slim_rpc_fn_method_bidistreamhandler_send(uint64_t ptr, RustBuffer data, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_BIDISTREAMHANDLER_SEND_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_BIDISTREAMHANDLER_SEND_ASYNC
uint64_t uniffi_slim_rpc_fn_method_bidistreamhandler_send_async(uint64_t ptr, RustBuffer data
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_CLONE_MULTICASTBIDISTREAMHANDLER
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_CLONE_MULTICASTBIDISTREAMHANDLER
uint64_t uniffi_slim_rpc_fn_clone_multicastbidistreamhandler(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_FREE_MULTICASTBIDISTREAMHANDLER
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_FREE_MULTICASTBIDISTREAMHANDLER
void uniffi_slim_rpc_fn_free_multicastbidistreamhandler(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_MULTICASTBIDISTREAMHANDLER_CLOSE_SEND
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_MULTICASTBIDISTREAMHANDLER_CLOSE_SEND
void uniffi_slim_rpc_fn_method_multicastbidistreamhandler_close_send(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_MULTICASTBIDISTREAMHANDLER_CLOSE_SEND_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_MULTICASTBIDISTREAMHANDLER_CLOSE_SEND_ASYNC
uint64_t uniffi_slim_rpc_fn_method_multicastbidistreamhandler_close_send_async(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_MULTICASTBIDISTREAMHANDLER_RECV
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_MULTICASTBIDISTREAMHANDLER_RECV
RustBuffer uniffi_slim_rpc_fn_method_multicastbidistreamhandler_recv(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_MULTICASTBIDISTREAMHANDLER_RECV_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_MULTICASTBIDISTREAMHANDLER_RECV_ASYNC
uint64_t uniffi_slim_rpc_fn_method_multicastbidistreamhandler_recv_async(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_MULTICASTBIDISTREAMHANDLER_SEND
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_MULTICASTBIDISTREAMHANDLER_SEND
void uniffi_slim_rpc_fn_method_multicastbidistreamhandler_send(uint64_t ptr, RustBuffer data, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_MULTICASTBIDISTREAMHANDLER_SEND_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_MULTICASTBIDISTREAMHANDLER_SEND_ASYNC
uint64_t uniffi_slim_rpc_fn_method_multicastbidistreamhandler_send_async(uint64_t ptr, RustBuffer data
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_CLONE_MULTICASTRESPONSEREADER
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_CLONE_MULTICASTRESPONSEREADER
uint64_t uniffi_slim_rpc_fn_clone_multicastresponsereader(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_FREE_MULTICASTRESPONSEREADER
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_FREE_MULTICASTRESPONSEREADER
void uniffi_slim_rpc_fn_free_multicastresponsereader(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_MULTICASTRESPONSEREADER_NEXT
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_MULTICASTRESPONSEREADER_NEXT
RustBuffer uniffi_slim_rpc_fn_method_multicastresponsereader_next(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_MULTICASTRESPONSEREADER_NEXT_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_MULTICASTRESPONSEREADER_NEXT_ASYNC
uint64_t uniffi_slim_rpc_fn_method_multicastresponsereader_next_async(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_CLONE_REQUESTSTREAM
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_CLONE_REQUESTSTREAM
uint64_t uniffi_slim_rpc_fn_clone_requeststream(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_FREE_REQUESTSTREAM
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_FREE_REQUESTSTREAM
void uniffi_slim_rpc_fn_free_requeststream(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_REQUESTSTREAM_NEXT
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_REQUESTSTREAM_NEXT
RustBuffer uniffi_slim_rpc_fn_method_requeststream_next(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_REQUESTSTREAM_NEXT_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_REQUESTSTREAM_NEXT_ASYNC
uint64_t uniffi_slim_rpc_fn_method_requeststream_next_async(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_CLONE_REQUESTSTREAMWRITER
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_CLONE_REQUESTSTREAMWRITER
uint64_t uniffi_slim_rpc_fn_clone_requeststreamwriter(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_FREE_REQUESTSTREAMWRITER
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_FREE_REQUESTSTREAMWRITER
void uniffi_slim_rpc_fn_free_requeststreamwriter(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_REQUESTSTREAMWRITER_FINALIZE_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_REQUESTSTREAMWRITER_FINALIZE_ASYNC
uint64_t uniffi_slim_rpc_fn_method_requeststreamwriter_finalize_async(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_REQUESTSTREAMWRITER_FINALIZE_STREAM
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_REQUESTSTREAMWRITER_FINALIZE_STREAM
RustBuffer uniffi_slim_rpc_fn_method_requeststreamwriter_finalize_stream(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_REQUESTSTREAMWRITER_FINALIZE_STREAM_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_REQUESTSTREAMWRITER_FINALIZE_STREAM_ASYNC
uint64_t uniffi_slim_rpc_fn_method_requeststreamwriter_finalize_stream_async(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_REQUESTSTREAMWRITER_SEND
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_REQUESTSTREAMWRITER_SEND
void uniffi_slim_rpc_fn_method_requeststreamwriter_send(uint64_t ptr, RustBuffer data, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_REQUESTSTREAMWRITER_SEND_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_REQUESTSTREAMWRITER_SEND_ASYNC
uint64_t uniffi_slim_rpc_fn_method_requeststreamwriter_send_async(uint64_t ptr, RustBuffer data
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_CLONE_RESPONSESINK
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_CLONE_RESPONSESINK
uint64_t uniffi_slim_rpc_fn_clone_responsesink(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_FREE_RESPONSESINK
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_FREE_RESPONSESINK
void uniffi_slim_rpc_fn_free_responsesink(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_RESPONSESINK_CLOSE
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_RESPONSESINK_CLOSE
void uniffi_slim_rpc_fn_method_responsesink_close(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_RESPONSESINK_CLOSE_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_RESPONSESINK_CLOSE_ASYNC
uint64_t uniffi_slim_rpc_fn_method_responsesink_close_async(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_RESPONSESINK_IS_CLOSED
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_RESPONSESINK_IS_CLOSED
int8_t uniffi_slim_rpc_fn_method_responsesink_is_closed(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_RESPONSESINK_IS_CLOSED_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_RESPONSESINK_IS_CLOSED_ASYNC
uint64_t uniffi_slim_rpc_fn_method_responsesink_is_closed_async(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_RESPONSESINK_SEND
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_RESPONSESINK_SEND
void uniffi_slim_rpc_fn_method_responsesink_send(uint64_t ptr, RustBuffer data, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_RESPONSESINK_SEND_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_RESPONSESINK_SEND_ASYNC
uint64_t uniffi_slim_rpc_fn_method_responsesink_send_async(uint64_t ptr, RustBuffer data
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_RESPONSESINK_SEND_ERROR
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_RESPONSESINK_SEND_ERROR
void uniffi_slim_rpc_fn_method_responsesink_send_error(uint64_t ptr, RustBuffer error, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_RESPONSESINK_SEND_ERROR_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_RESPONSESINK_SEND_ERROR_ASYNC
uint64_t uniffi_slim_rpc_fn_method_responsesink_send_error_async(uint64_t ptr, RustBuffer error
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_CLONE_RESPONSESTREAMREADER
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_CLONE_RESPONSESTREAMREADER
uint64_t uniffi_slim_rpc_fn_clone_responsestreamreader(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_FREE_RESPONSESTREAMREADER
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_FREE_RESPONSESTREAMREADER
void uniffi_slim_rpc_fn_free_responsestreamreader(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_RESPONSESTREAMREADER_NEXT
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_RESPONSESTREAMREADER_NEXT
RustBuffer uniffi_slim_rpc_fn_method_responsestreamreader_next(uint64_t ptr, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_RESPONSESTREAMREADER_NEXT_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_FN_METHOD_RESPONSESTREAMREADER_NEXT_ASYNC
uint64_t uniffi_slim_rpc_fn_method_responsestreamreader_next_async(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUSTBUFFER_ALLOC
RustBuffer ffi_slim_rpc_rustbuffer_alloc(uint64_t size, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_slim_rpc_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUSTBUFFER_FREE
void ffi_slim_rpc_rustbuffer_free(RustBuffer buf, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUSTBUFFER_RESERVE
RustBuffer ffi_slim_rpc_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_POLL_U8
void ffi_slim_rpc_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_CANCEL_U8
void ffi_slim_rpc_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_FREE_U8
void ffi_slim_rpc_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_slim_rpc_rust_future_complete_u8(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_POLL_I8
void ffi_slim_rpc_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_CANCEL_I8
void ffi_slim_rpc_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_FREE_I8
void ffi_slim_rpc_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_COMPLETE_I8
int8_t ffi_slim_rpc_rust_future_complete_i8(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_POLL_U16
void ffi_slim_rpc_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_CANCEL_U16
void ffi_slim_rpc_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_FREE_U16
void ffi_slim_rpc_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_slim_rpc_rust_future_complete_u16(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_POLL_I16
void ffi_slim_rpc_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_CANCEL_I16
void ffi_slim_rpc_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_FREE_I16
void ffi_slim_rpc_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_COMPLETE_I16
int16_t ffi_slim_rpc_rust_future_complete_i16(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_POLL_U32
void ffi_slim_rpc_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_CANCEL_U32
void ffi_slim_rpc_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_FREE_U32
void ffi_slim_rpc_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_slim_rpc_rust_future_complete_u32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_POLL_I32
void ffi_slim_rpc_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_CANCEL_I32
void ffi_slim_rpc_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_FREE_I32
void ffi_slim_rpc_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_COMPLETE_I32
int32_t ffi_slim_rpc_rust_future_complete_i32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_POLL_U64
void ffi_slim_rpc_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_CANCEL_U64
void ffi_slim_rpc_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_FREE_U64
void ffi_slim_rpc_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_slim_rpc_rust_future_complete_u64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_POLL_I64
void ffi_slim_rpc_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_CANCEL_I64
void ffi_slim_rpc_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_FREE_I64
void ffi_slim_rpc_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_COMPLETE_I64
int64_t ffi_slim_rpc_rust_future_complete_i64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_POLL_F32
void ffi_slim_rpc_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_CANCEL_F32
void ffi_slim_rpc_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_FREE_F32
void ffi_slim_rpc_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_COMPLETE_F32
float ffi_slim_rpc_rust_future_complete_f32(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_POLL_F64
void ffi_slim_rpc_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_CANCEL_F64
void ffi_slim_rpc_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_FREE_F64
void ffi_slim_rpc_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_COMPLETE_F64
double ffi_slim_rpc_rust_future_complete_f64(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_slim_rpc_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_slim_rpc_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_slim_rpc_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_slim_rpc_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_POLL_VOID
void ffi_slim_rpc_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_CANCEL_VOID
void ffi_slim_rpc_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_FREE_VOID
void ffi_slim_rpc_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_RUST_FUTURE_COMPLETE_VOID
void ffi_slim_rpc_rust_future_complete_void(uint64_t handle, RustCallStatus *out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_CHANNEL_CALL_MULTICAST_STREAM_STREAM
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_CHANNEL_CALL_MULTICAST_STREAM_STREAM
uint16_t uniffi_slim_rpc_checksum_method_channel_call_multicast_stream_stream(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_CHANNEL_CALL_MULTICAST_STREAM_UNARY
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_CHANNEL_CALL_MULTICAST_STREAM_UNARY
uint16_t uniffi_slim_rpc_checksum_method_channel_call_multicast_stream_unary(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_CHANNEL_CALL_MULTICAST_UNARY
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_CHANNEL_CALL_MULTICAST_UNARY
uint16_t uniffi_slim_rpc_checksum_method_channel_call_multicast_unary(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_CHANNEL_CALL_MULTICAST_UNARY_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_CHANNEL_CALL_MULTICAST_UNARY_ASYNC
uint16_t uniffi_slim_rpc_checksum_method_channel_call_multicast_unary_async(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_CHANNEL_CALL_MULTICAST_UNARY_STREAM
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_CHANNEL_CALL_MULTICAST_UNARY_STREAM
uint16_t uniffi_slim_rpc_checksum_method_channel_call_multicast_unary_stream(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_CHANNEL_CALL_MULTICAST_UNARY_STREAM_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_CHANNEL_CALL_MULTICAST_UNARY_STREAM_ASYNC
uint16_t uniffi_slim_rpc_checksum_method_channel_call_multicast_unary_stream_async(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_CHANNEL_CALL_STREAM_STREAM
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_CHANNEL_CALL_STREAM_STREAM
uint16_t uniffi_slim_rpc_checksum_method_channel_call_stream_stream(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_CHANNEL_CALL_STREAM_UNARY
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_CHANNEL_CALL_STREAM_UNARY
uint16_t uniffi_slim_rpc_checksum_method_channel_call_stream_unary(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_CHANNEL_CALL_UNARY
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_CHANNEL_CALL_UNARY
uint16_t uniffi_slim_rpc_checksum_method_channel_call_unary(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_CHANNEL_CALL_UNARY_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_CHANNEL_CALL_UNARY_ASYNC
uint16_t uniffi_slim_rpc_checksum_method_channel_call_unary_async(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_CHANNEL_CALL_UNARY_STREAM
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_CHANNEL_CALL_UNARY_STREAM
uint16_t uniffi_slim_rpc_checksum_method_channel_call_unary_stream(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_CHANNEL_CALL_UNARY_STREAM_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_CHANNEL_CALL_UNARY_STREAM_ASYNC
uint16_t uniffi_slim_rpc_checksum_method_channel_call_unary_stream_async(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_CHANNEL_CLOSE_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_CHANNEL_CLOSE_ASYNC
uint16_t uniffi_slim_rpc_checksum_method_channel_close_async(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_CHANNEL_CLOSE_BLOCKING
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_CHANNEL_CLOSE_BLOCKING
uint16_t uniffi_slim_rpc_checksum_method_channel_close_blocking(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_CONTEXT_DEADLINE
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_CONTEXT_DEADLINE
uint16_t uniffi_slim_rpc_checksum_method_context_deadline(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_CONTEXT_IS_DEADLINE_EXCEEDED
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_CONTEXT_IS_DEADLINE_EXCEEDED
uint16_t uniffi_slim_rpc_checksum_method_context_is_deadline_exceeded(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_CONTEXT_METADATA
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_CONTEXT_METADATA
uint16_t uniffi_slim_rpc_checksum_method_context_metadata(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_CONTEXT_REMAINING_TIME
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_CONTEXT_REMAINING_TIME
uint16_t uniffi_slim_rpc_checksum_method_context_remaining_time(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_CONTEXT_SESSION_ID
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_CONTEXT_SESSION_ID
uint16_t uniffi_slim_rpc_checksum_method_context_session_id(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_STREAMSTREAMHANDLER_HANDLE
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_STREAMSTREAMHANDLER_HANDLE
uint16_t uniffi_slim_rpc_checksum_method_streamstreamhandler_handle(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_STREAMUNARYHANDLER_HANDLE
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_STREAMUNARYHANDLER_HANDLE
uint16_t uniffi_slim_rpc_checksum_method_streamunaryhandler_handle(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_UNARYSTREAMHANDLER_HANDLE
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_UNARYSTREAMHANDLER_HANDLE
uint16_t uniffi_slim_rpc_checksum_method_unarystreamhandler_handle(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_UNARYUNARYHANDLER_HANDLE
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_UNARYUNARYHANDLER_HANDLE
uint16_t uniffi_slim_rpc_checksum_method_unaryunaryhandler_handle(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_SERVER_REGISTER_STREAM_STREAM
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_SERVER_REGISTER_STREAM_STREAM
uint16_t uniffi_slim_rpc_checksum_method_server_register_stream_stream(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_SERVER_REGISTER_STREAM_UNARY
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_SERVER_REGISTER_STREAM_UNARY
uint16_t uniffi_slim_rpc_checksum_method_server_register_stream_unary(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_SERVER_REGISTER_UNARY_STREAM
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_SERVER_REGISTER_UNARY_STREAM
uint16_t uniffi_slim_rpc_checksum_method_server_register_unary_stream(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_SERVER_REGISTER_UNARY_UNARY
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_SERVER_REGISTER_UNARY_UNARY
uint16_t uniffi_slim_rpc_checksum_method_server_register_unary_unary(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_SERVER_SERVE_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_SERVER_SERVE_ASYNC
uint16_t uniffi_slim_rpc_checksum_method_server_serve_async(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_SERVER_SERVE_BLOCKING
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_SERVER_SERVE_BLOCKING
uint16_t uniffi_slim_rpc_checksum_method_server_serve_blocking(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_SERVER_SHUTDOWN_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_SERVER_SHUTDOWN_ASYNC
uint16_t uniffi_slim_rpc_checksum_method_server_shutdown_async(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_SERVER_SHUTDOWN_BLOCKING
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_SERVER_SHUTDOWN_BLOCKING
uint16_t uniffi_slim_rpc_checksum_method_server_shutdown_blocking(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_BIDISTREAMHANDLER_CLOSE_SEND
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_BIDISTREAMHANDLER_CLOSE_SEND
uint16_t uniffi_slim_rpc_checksum_method_bidistreamhandler_close_send(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_BIDISTREAMHANDLER_CLOSE_SEND_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_BIDISTREAMHANDLER_CLOSE_SEND_ASYNC
uint16_t uniffi_slim_rpc_checksum_method_bidistreamhandler_close_send_async(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_BIDISTREAMHANDLER_RECV
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_BIDISTREAMHANDLER_RECV
uint16_t uniffi_slim_rpc_checksum_method_bidistreamhandler_recv(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_BIDISTREAMHANDLER_RECV_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_BIDISTREAMHANDLER_RECV_ASYNC
uint16_t uniffi_slim_rpc_checksum_method_bidistreamhandler_recv_async(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_BIDISTREAMHANDLER_SEND
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_BIDISTREAMHANDLER_SEND
uint16_t uniffi_slim_rpc_checksum_method_bidistreamhandler_send(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_BIDISTREAMHANDLER_SEND_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_BIDISTREAMHANDLER_SEND_ASYNC
uint16_t uniffi_slim_rpc_checksum_method_bidistreamhandler_send_async(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_MULTICASTBIDISTREAMHANDLER_CLOSE_SEND
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_MULTICASTBIDISTREAMHANDLER_CLOSE_SEND
uint16_t uniffi_slim_rpc_checksum_method_multicastbidistreamhandler_close_send(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_MULTICASTBIDISTREAMHANDLER_CLOSE_SEND_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_MULTICASTBIDISTREAMHANDLER_CLOSE_SEND_ASYNC
uint16_t uniffi_slim_rpc_checksum_method_multicastbidistreamhandler_close_send_async(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_MULTICASTBIDISTREAMHANDLER_RECV
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_MULTICASTBIDISTREAMHANDLER_RECV
uint16_t uniffi_slim_rpc_checksum_method_multicastbidistreamhandler_recv(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_MULTICASTBIDISTREAMHANDLER_RECV_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_MULTICASTBIDISTREAMHANDLER_RECV_ASYNC
uint16_t uniffi_slim_rpc_checksum_method_multicastbidistreamhandler_recv_async(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_MULTICASTBIDISTREAMHANDLER_SEND
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_MULTICASTBIDISTREAMHANDLER_SEND
uint16_t uniffi_slim_rpc_checksum_method_multicastbidistreamhandler_send(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_MULTICASTBIDISTREAMHANDLER_SEND_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_MULTICASTBIDISTREAMHANDLER_SEND_ASYNC
uint16_t uniffi_slim_rpc_checksum_method_multicastbidistreamhandler_send_async(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_MULTICASTRESPONSEREADER_NEXT
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_MULTICASTRESPONSEREADER_NEXT
uint16_t uniffi_slim_rpc_checksum_method_multicastresponsereader_next(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_MULTICASTRESPONSEREADER_NEXT_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_MULTICASTRESPONSEREADER_NEXT_ASYNC
uint16_t uniffi_slim_rpc_checksum_method_multicastresponsereader_next_async(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_REQUESTSTREAM_NEXT
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_REQUESTSTREAM_NEXT
uint16_t uniffi_slim_rpc_checksum_method_requeststream_next(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_REQUESTSTREAM_NEXT_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_REQUESTSTREAM_NEXT_ASYNC
uint16_t uniffi_slim_rpc_checksum_method_requeststream_next_async(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_REQUESTSTREAMWRITER_FINALIZE_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_REQUESTSTREAMWRITER_FINALIZE_ASYNC
uint16_t uniffi_slim_rpc_checksum_method_requeststreamwriter_finalize_async(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_REQUESTSTREAMWRITER_FINALIZE_STREAM
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_REQUESTSTREAMWRITER_FINALIZE_STREAM
uint16_t uniffi_slim_rpc_checksum_method_requeststreamwriter_finalize_stream(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_REQUESTSTREAMWRITER_FINALIZE_STREAM_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_REQUESTSTREAMWRITER_FINALIZE_STREAM_ASYNC
uint16_t uniffi_slim_rpc_checksum_method_requeststreamwriter_finalize_stream_async(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_REQUESTSTREAMWRITER_SEND
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_REQUESTSTREAMWRITER_SEND
uint16_t uniffi_slim_rpc_checksum_method_requeststreamwriter_send(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_REQUESTSTREAMWRITER_SEND_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_REQUESTSTREAMWRITER_SEND_ASYNC
uint16_t uniffi_slim_rpc_checksum_method_requeststreamwriter_send_async(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_RESPONSESINK_CLOSE
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_RESPONSESINK_CLOSE
uint16_t uniffi_slim_rpc_checksum_method_responsesink_close(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_RESPONSESINK_CLOSE_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_RESPONSESINK_CLOSE_ASYNC
uint16_t uniffi_slim_rpc_checksum_method_responsesink_close_async(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_RESPONSESINK_IS_CLOSED
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_RESPONSESINK_IS_CLOSED
uint16_t uniffi_slim_rpc_checksum_method_responsesink_is_closed(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_RESPONSESINK_IS_CLOSED_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_RESPONSESINK_IS_CLOSED_ASYNC
uint16_t uniffi_slim_rpc_checksum_method_responsesink_is_closed_async(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_RESPONSESINK_SEND
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_RESPONSESINK_SEND
uint16_t uniffi_slim_rpc_checksum_method_responsesink_send(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_RESPONSESINK_SEND_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_RESPONSESINK_SEND_ASYNC
uint16_t uniffi_slim_rpc_checksum_method_responsesink_send_async(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_RESPONSESINK_SEND_ERROR
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_RESPONSESINK_SEND_ERROR
uint16_t uniffi_slim_rpc_checksum_method_responsesink_send_error(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_RESPONSESINK_SEND_ERROR_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_RESPONSESINK_SEND_ERROR_ASYNC
uint16_t uniffi_slim_rpc_checksum_method_responsesink_send_error_async(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_RESPONSESTREAMREADER_NEXT
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_RESPONSESTREAMREADER_NEXT
uint16_t uniffi_slim_rpc_checksum_method_responsestreamreader_next(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_RESPONSESTREAMREADER_NEXT_ASYNC
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_METHOD_RESPONSESTREAMREADER_NEXT_ASYNC
uint16_t uniffi_slim_rpc_checksum_method_responsestreamreader_next_async(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_CONSTRUCTOR_CHANNEL_NEW
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_CONSTRUCTOR_CHANNEL_NEW
uint16_t uniffi_slim_rpc_checksum_constructor_channel_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_CONSTRUCTOR_CHANNEL_NEW_GROUP
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_CONSTRUCTOR_CHANNEL_NEW_GROUP
uint16_t uniffi_slim_rpc_checksum_constructor_channel_new_group(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_CONSTRUCTOR_CHANNEL_NEW_GROUP_WITH_CONNECTION
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_CONSTRUCTOR_CHANNEL_NEW_GROUP_WITH_CONNECTION
uint16_t uniffi_slim_rpc_checksum_constructor_channel_new_group_with_connection(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_CONSTRUCTOR_CHANNEL_NEW_WITH_CONNECTION
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_CONSTRUCTOR_CHANNEL_NEW_WITH_CONNECTION
uint16_t uniffi_slim_rpc_checksum_constructor_channel_new_with_connection(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_CONSTRUCTOR_SERVER_NEW
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_CONSTRUCTOR_SERVER_NEW
uint16_t uniffi_slim_rpc_checksum_constructor_server_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_CONSTRUCTOR_SERVER_NEW_WITH_CONNECTION
#define UNIFFI_FFIDEF_UNIFFI_SLIM_RPC_CHECKSUM_CONSTRUCTOR_SERVER_NEW_WITH_CONNECTION
uint16_t uniffi_slim_rpc_checksum_constructor_server_new_with_connection(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_SLIM_RPC_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_SLIM_RPC_UNIFFI_CONTRACT_VERSION
uint32_t ffi_slim_rpc_uniffi_contract_version(void
    
);
#endif

 void slim_rpc_handler_traits_cgo_dispatchCallbackInterfaceStreamStreamHandlerMethod0(uint64_t uniffi_handle, uint64_t stream, uint64_t context, uint64_t sink, UniffiForeignFutureCompleteVoid uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFutureDroppedCallbackStruct* uniffi_out_dropped_callback);
 void slim_rpc_handler_traits_cgo_dispatchCallbackInterfaceStreamStreamHandlerFree(uint64_t handle);
uint64_t slim_rpc_handler_traits_cgo_dispatchCallbackInterfaceStreamStreamHandlerClone(uint64_t handle);
 void slim_rpc_handler_traits_cgo_dispatchCallbackInterfaceStreamUnaryHandlerMethod0(uint64_t uniffi_handle, uint64_t stream, uint64_t context, UniffiForeignFutureCompleteRustBuffer uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFutureDroppedCallbackStruct* uniffi_out_dropped_callback);
 void slim_rpc_handler_traits_cgo_dispatchCallbackInterfaceStreamUnaryHandlerFree(uint64_t handle);
uint64_t slim_rpc_handler_traits_cgo_dispatchCallbackInterfaceStreamUnaryHandlerClone(uint64_t handle);
 void slim_rpc_handler_traits_cgo_dispatchCallbackInterfaceUnaryStreamHandlerMethod0(uint64_t uniffi_handle, RustBuffer request, uint64_t context, uint64_t sink, UniffiForeignFutureCompleteVoid uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFutureDroppedCallbackStruct* uniffi_out_dropped_callback);
 void slim_rpc_handler_traits_cgo_dispatchCallbackInterfaceUnaryStreamHandlerFree(uint64_t handle);
uint64_t slim_rpc_handler_traits_cgo_dispatchCallbackInterfaceUnaryStreamHandlerClone(uint64_t handle);
 void slim_rpc_handler_traits_cgo_dispatchCallbackInterfaceUnaryUnaryHandlerMethod0(uint64_t uniffi_handle, RustBuffer request, uint64_t context, UniffiForeignFutureCompleteRustBuffer uniffi_future_callback, uint64_t uniffi_callback_data, UniffiForeignFutureDroppedCallbackStruct* uniffi_out_dropped_callback);
 void slim_rpc_handler_traits_cgo_dispatchCallbackInterfaceUnaryUnaryHandlerFree(uint64_t handle);
uint64_t slim_rpc_handler_traits_cgo_dispatchCallbackInterfaceUnaryUnaryHandlerClone(uint64_t handle);

void slim_rpc_uniffiFutureContinuationCallback(uint64_t, int8_t);
void slim_rpc_uniffiFreeGorutine(uint64_t);
